// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InspectionCompleteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void inspectionComplete() {
    driver.get("http://devreassure.innov.co.in/complaints/view/696");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".quick-links-container > .icon-menu > .ng-star-inserted:nth-child(3) .link-title")).click();
    js.executeScript("window.scrollTo(0,1221.25)");
    driver.findElement(By.cssSelector(".ng-tns-c125-38:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#mat-option-5 > .mat-option-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-menu-trigger .mat-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ng-tns-c125-42:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#mat-option-12 > .mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-option-13 > .mat-option-text")).click();
    driver.findElement(By.cssSelector(".cdk-overlay-backdrop")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-tns-c103-20 > .group-menu-action-section > .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ng-tns-c125-44 > .mat-select-arrow")).click();
    driver.findElement(By.cssSelector("#mat-option-17 > .mat-option-text")).click();
    driver.findElement(By.cssSelector(".ng-tns-c125-46:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#mat-option-21 > .mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-option-23 > .mat-option-text")).click();
    driver.findElement(By.cssSelector(".ng-tns-c125-48:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".cdk-overlay-backdrop")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-tns-c103-20 > .group-menu-action-section > .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ng-tns-c125-48 > .mat-select-arrow")).click();
    driver.findElement(By.cssSelector("#mat-option-40 > .mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-option-42 > .mat-option-text")).click();
    driver.findElement(By.cssSelector(".cdk-overlay-backdrop")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-menu-trigger .mat-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(11) > .file-data > .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("mat-input-6")).click();
    driver.findElement(By.id("mat-input-6")).sendKeys("this is a dummy text");
    driver.findElement(By.cssSelector(".ng-tns-c72-49 > .mat-form-field-wrapper")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(10) > .file-data > .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".mat-accent > .mat-button-wrapper > .mat-icon")).click();
    driver.findElement(By.cssSelector(".mat-dialog-content > input")).sendKeys("C:\\fakepath\\dummy.pdf");
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(13) .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(11) > .file-data > .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".mat-accent > .mat-button-wrapper > .mat-icon")).click();
    driver.findElement(By.cssSelector(".mat-dialog-content > input")).sendKeys("C:\\fakepath\\Firefox Installer.exe");
    driver.findElement(By.xpath("//span[contains(.,\'Please upload a file with valid format.\')]")).click();
    js.executeScript("window.scrollTo(0,1621.25)");
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-dialog-actions > .mat-primary > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
    js.executeScript("window.scrollTo(0,1621.25)");
    {
      WebElement element = driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused")).click();
    driver.findElement(By.cssSelector(".cdk-focused")).click();
    driver.findElement(By.cssSelector(".mat-dialog-content > input")).sendKeys("C:\\fakepath\\SampleJPGImage_50kbmb.jpg");
    driver.findElement(By.cssSelector(".cdk-focused .mat-icon")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to delete this item?"));
    driver.switchTo().alert().dismiss();
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted > .mat-mini-fab .mat-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused .mat-icon")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to delete this item?"));
    driver.switchTo().alert().accept();
    driver.switchTo().alert().dismiss();
    {
      WebElement element = driver.findElement(By.cssSelector(".cdk-focused"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".cdk-focused .mat-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused .mat-icon")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".cdk-focused"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused")).click();
    driver.findElement(By.cssSelector(".mat-dialog-content > input")).sendKeys("C:\\fakepath\\SampleJPGImage_50kbmb.jpg");
    driver.findElement(By.cssSelector(".cdk-focused")).click();
    js.executeScript("window.scrollTo(0,1621.25)");
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(12) .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(12) .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".cdk-focused"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(12) .mat-focus-indicator:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-accent > .mat-button-wrapper > .mat-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".mat-accent > .mat-button-wrapper > .mat-icon")).click();
    driver.findElement(By.cssSelector(".mat-dialog-content > input")).sendKeys("C:\\fakepath\\file_example_JPG_100kB.jpg");
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
    js.executeScript("window.scrollTo(0,1621.25)");
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(10) .mat-focus-indicator:nth-child(3) .mat-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".form-sub-actions > .mat-focus-indicator:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused")).click();
    driver.findElement(By.xpath("//p[contains(.,\'Inspection has been created successfully.\')]")).click();
    driver.findElement(By.cssSelector("#modal-action-button > .mat-button-wrapper")).click();
  }
}
